### ISSUE TITLE
Cannot find module 'jsdoc/util/doop'

### ISSUE THREAD

**Issue by jnschrag** [happydata/nomielab#1]
I'm a huge fan of nomie, so I wanted to give this app a try, but each time I've run into the same issue (I've tried it from scratch 3 times). Bower and Node/NPM are installed. After running the gulp serve command, this is the error that I get:

```
Removed:nomielab $ gulp serve
module.js:340
    throw err;
    ^

Error: Cannot find module 'jsdoc/util/doop'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (-Removed-/nomielab/node_modules/jsdoc/lib/jsdoc/borrow.js:9:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

Any thoughts on how to fix this? It could very well be something I'm doing, but I'm not sure what.

**Comment by brandoncorbin** [comment]
@jnschrag That error is with jsdoc - which I will be removing. I've done an awful job at keeping this repo up-to-date, and for that I'm sorry. My goal is to have my most recent version pushed by the end of the weekend.

**Comment by jnschrag** [comment]
No worries! Thanks for letting me know. I look forward to the updated repo whenever you get a chance. :)
